FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 5000

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["MyApp.csproj", "./"]
RUN dotnet restore "HusbandsGroceryApp.csproj"
COPY . .
RUN dotnet build "HusbandsGroceryApp.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MyAppHusbandsGroceryAppcsproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "HusbandsGroceryApp.dll"]
